### ISSUE TITLE
Error if pex file is not a sibling to science config

### ISSUE THREAD

**Issue by sureshjoshi** [a-scie/lift#2]
While testing out a `scie` plugin using Pants, I noticed that I get an error if the target pex file is in a different directory. Not sure if that's intentional or not - in case the desired state is to have all files as siblings.

The problem appears to be symlinking to a directory that may not exist at `tempdir/{PROBLEMATIC_PATH}/mypex.pex`.

## Workaround

```python
# __main__.py

for file in files:
    if file.source is None:
        path = file_paths_by_id.get(file.id) or Path.cwd() / file.name
        if not path.exists():
            raise ValueError(f"The file for {file.id} is not mapped or cannot be found.")
        target = chroot / file.name
        target.parent.mkdir(parents=True, exist_ok=True) ### <- Workaround
        if not target.exists():
            target.symlink_to(path)
```

## Config File

```toml
# science.toml

[science]
name = "science"
description = "Ship your interpreted executables using science."
platforms = [
    "linux-aarch64",
    "linux-x86_64",
    "macos-aarch64",
    "macos-x86_64",
]

[[science.interpreters]]
id = "cpython"
provider = "PythonBuildStandalone"
lazy = true
version = "3.11"

[[science.files]]
name = "dist/science.pex"

[[science.commands]]
exe = "#{cpython:python}"
args = [
    "{dist/science.pex}",
]
env.remove_re = [
    "PEX_.*",
]
[science.commands.env.replace]
PEX_ROOT = "{scie.bindings}/pex_root"
PEX_PYTHON_PATH = "#{cpython:python}"
```

## Error (only if Workaround is not applied)

```bash
⏺ scratch/lift % ./dist/science.pex build science.toml
Traceback (most recent call last):
  File "/Users/sj/.pex/venvs/71d9ceded48a6e250231642a507b5266cd578eda/779eb2cc0ca9e2fdd204774cbc41848e4e7c5055/pex", line 274, in <module>
    runpy.run_module(module_name, run_name="__main__", alter_sys=True)
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/sj/.pex/venvs/71d9ceded48a6e250231642a507b5266cd578eda/779eb2cc0ca9e2fdd204774cbc41848e4e7c5055/lib/python3.11/site-packages/science/__main__.py", line 196, in <module>
    main()
  File "/Users/sj/.pex/venvs/71d9ceded48a6e250231642a507b5266cd578eda/779eb2cc0ca9e2fdd204774cbc41848e4e7c5055/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sj/.pex/venvs/71d9ceded48a6e250231642a507b5266cd578eda/779eb2cc0ca9e2fdd204774cbc41848e4e7c5055/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/sj/.pex/venvs/71d9ceded48a6e250231642a507b5266cd578eda/779eb2cc0ca9e2fdd204774cbc41848e4e7c5055/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sj/.pex/venvs/71d9ceded48a6e250231642a507b5266cd578eda/779eb2cc0ca9e2fdd204774cbc41848e4e7c5055/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sj/.pex/venvs/71d9ceded48a6e250231642a507b5266cd578eda/779eb2cc0ca9e2fdd204774cbc41848e4e7c5055/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sj/.pex/venvs/71d9ceded48a6e250231642a507b5266cd578eda/779eb2cc0ca9e2fdd204774cbc41848e4e7c5055/lib/python3.11/site-packages/science/__main__.py", line 174, in build
    for platform, lift_manifest in _export(application, file_mappings, td):
  File "/Users/sj/.pex/venvs/71d9ceded48a6e250231642a507b5266cd578eda/779eb2cc0ca9e2fdd204774cbc41848e4e7c5055/lib/python3.11/site-packages/science/__main__.py", line 121, in _export
    target.symlink_to(path)
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pathlib.py", line 1198, in symlink_to
    os.symlink(target, self, target_is_directory)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sj/Developer/scratch/lift/dist/science.pex' -> '/var/folders/dy/q08y_dts5vd71rm99t4gc9lr0000gp/T/tmpo0tg171r/linux-aarch64/dist/science.pex'
```

**Comment by jsirois** [comment]
Sorry @sureshjoshi, I totally missed this. I think you may have missed the `--file name=path` option for build. That said, the error should be cleaned up regardless.

**Comment by sureshjoshi** [comment]
> Sorry @sureshjoshi, I totally missed this.

No worries, it took me a minute to remember that I wrote it!

> I think you may have missed the --file name=path option for the build subcommand.

Yes, I definitely did - I thought using the toml file alone would be enough to setup the out-of-directory file configuration. 

Using the `--build` would fit my purposes and clean up some `fs` code.

**Comment by jsirois** [comment]
Ok, I didn't understand the issue before for some reason but now I do. I'm a little confused why you didn't just fix it. That threw me off here. You almost did more work above filing than it would be to fix! @sureshjoshi are you willing to throw up a PR?
